### PR TITLE
More realistic paper simulation

### PR DESCRIPTION
**Pull request by liliakai**
Use dot image sampled from an image of actual dot matrix printer paper.

Also adds some color on h3's, which looks pretty good against latest test site data, but may need to be scoped to a different selector if the content changes a lot...

### CODE REVIEW

**Comment by nooitaf** [comment]
Thanks :)
Can you also add the image `dot6.png`

**Comment by nooitaf** [comment]
The content should not change a lot. except the submission of the users ofc.

I also didn't add any color (accept the delete button) so we could "play" with the background-color (randomize or something). Or maybe even let the user set their own bgcolor in their profile. Didnt get that far yet but that was the idea behind "no-colors". I'll merge as soon as you add the dot6 and then lets see what community says ;)

**Comment by liliakai** [comment]
dot6 is added in 947e54a6cc0930b87ea6079a03d00677ab45bdc8

**Comment by nooitaf** [comment]
oh, so sry..

**Pull request merged**
